function APPLY_CAL()
    %% 1. Setup and Path Configuration
    close all; clear; clc;

    defaultPath = 'G:\Shared drives\Corp Main\Engineering\LAB Equipment\Tools\UV Collection Calibration [cts uJ]\process Cal in matlab';
    if ~exist(defaultPath, 'dir'), startPath = pwd; else, startPath = defaultPath; end
    
    %% 2. Read Inputs (In Sequence)
    currentPath = startPath; 

    % 1. Load System Responsivity (Generated by Script 1 - CSV)
    [file1, path1] = uigetfile(fullfile(currentPath, '*.csv'), 'Select System Responsivity CSV');
    if isequal(file1, 0), return; end
    raw1 = importdata(fullfile(path1, file1));
    A_Resp = raw1.data; 
    currentPath = path1; 
    
    % 2. Load Fiber10 Spectrum (NEW: QE Pro TXT Format)
    [file2, path2] = uigetfile(fullfile(currentPath, '*.txt'), 'Select Fiber10 Spectrum (QEPro TXT)');
    if isequal(file2, 0), return; end
    fiberData = readQEPro_SpectrumFile(fullfile(path2, file2));
    A_Fiber10 = fiberData.A;
    Tint_Fiber10 = fiberData.Tint; % Available if needed
    currentPath = path2;

    % 3. Load NEW DUT Spectrum (The measurement to be calibrated - TXT)
    [file3, path3] = uigetfile(fullfile(currentPath, '*.txt'), 'Select NEW DUT Spectrum (QEPro TXT)');
    if isequal(file3, 0), return; end
    dutData = readQEPro_SpectrumFile(fullfile(path3, file3));
    A_DUT = dutData.A;
    IntegrationTime = dutData.Tint;

    %% 3. Process and Interpolate
    % Master Wavelength Grid comes from the DUT measurement
    wl_master = A_DUT(:, 1);  
    raw_counts = A_DUT(:, 2);
    
    % Interpolate calibration data onto DUT grid
    % We use A_Resp(:,1) and A_Fiber10(:,1) as the source x-axis
    resp_interp    = interp1(A_Resp(:,1), A_Resp(:,2), wl_master, 'linear', 'extrap');
    fiber10_interp = interp1(A_Fiber10(:,1), A_Fiber10(:,2), wl_master, 'linear', 'extrap');

    fprintf('Data loaded. Fiber10 Tint: %.3fs | DUT Tint: %.3fs\n', Tint_Fiber10, IntegrationTime);

    %% 4. YOUR CALIBRATION LOGIC HERE
    % wl_master      -> nm
    % raw_counts     -> Counts
    % IntegrationTime -> Seconds
    % resp_interp    -> [cts / uJ] (Interpolated)
    % fiber10_interp -> Fiber 10 Spectrum/Counts (Interpolated)
    
    dut_cps = raw_counts ./ IntegrationTime;

    PowerTot_uW_Fiber10 = 0.011; 

    isValid = ~isnan(resp_interp) & ...
              ~isnan(dut_cps) & ...
              ~isnan(fiber10_interp) & ...
              (wl_master > 202);


    Response_DUT_cts_per_uJ = zeros(size(wl_master));
	CAL_Spectrum_raw = zeros(size(wl_master));          %like "I_lamp"    
    CAL_Spectrum_raw(isValid) = fiber10_interp(isValid);
                             
    total_raw_sum = sum(CAL_Spectrum_raw(isValid));
    CAL_Spectrum_normalized = CAL_Spectrum_raw ./ total_raw_sum;
    CAL_Spectrum_power = CAL_Spectrum_normalized * PowerTot_uW_Fiber10;

    canCalculateR = isValid & (CAL_Spectrum_power > 0);
    Response_DUT_cts_per_uJ(canCalculateR) = dut_cps(canCalculateR) ./ CAL_Spectrum_power(canCalculateR);
      
    %% 5. Visualization
    hFig = figure('Name', 'Calibrated Measurement');
    semilogy(wl_master, Response_DUT_cts_per_uJ, 'LineWidth', 1.5);
    grid on;
    ylabel('Calibrated Units');
    xlabel('Wavelength (nm)');
    title(['Processed: ', file3], 'Interpreter', 'none');
    xlim([200,700]); ylim([1e6,1e9]);
    
    hFig = figure('Name', 'Calibrated Measurement');
    subplot(2,1,1);
    semilogy(wl_master, Response_DUT_cts_per_uJ, 'LineWidth', 1.5); hold all;
    semilogy(wl_master, resp_interp , 'LineWidth', 1.5); hold all;
    grid on;   legend('DUT (with QE Pro)','QE Pro (alone)');
    ylabel('DUT Response: [cts/uJ]');
    xlabel('Wavelength (nm)');
    xlim([200,400]); ylim([1e6,1e9]);
    title(['Processed: ', file3], 'Interpreter', 'none');
    
    subplot(2,1,2);
    semilogy(wl_master, Response_DUT_cts_per_uJ./resp_interp, 'LineWidth', 1.5); hold all;
    xlim([200,400]); grid on;  ylabel('Transmission of Optics');
    title(['DUT(withQE Pro) v. QEPro Alone']);
 
    
    %% 6. Automatic Export
    [~, baseName, ~] = fileparts(file3);
    outputTable = table(wl_master, Response_DUT_cts_per_uJ, ...
        'VariableNames', {'Wavelength_nm', 'Calibrated_Value'});
    
    writetable(outputTable, fullfile(path3, [baseName, '_Processed.csv']));
    saveas(hFig, fullfile(path3, [baseName, '_Processed_Plot.png']));
    
    fprintf('Success! Files saved to: %s\n', path3);
end

%% --- Helper Functions (Use your existing ones below) ---
function dataObj = readQEPro_SpectrumFile(fullPath)
    dataObj.A = []; dataObj.Tint = NaN;
    fid = fopen(fullPath, 'r'); if fid == -1, return; end
    lineIdx = 0; dataStartLine = 0;
    while ~feof(fid) && lineIdx < 100
        line = fgetl(fid); lineIdx = lineIdx + 1;
        if contains(line, '(sec):')
            parts = strsplit(line, ':'); 
            dataObj.Tint = str2double(parts{end}); 
        end
        if ~isempty(line) && (isstrprop(line(1), 'digit') || line(1) == '-')
            dataStartLine = lineIdx; break; 
        end
    end
    fclose(fid);
    if dataStartLine > 0
        try
            dataObj.A = dlmread(fullPath, '\t', dataStartLine - 1, 0);
        catch
            dataObj.A = manual_parse(fullPath, dataStartLine);
        end
    end
end

function A = manual_parse(fullPath, startLine)
    fid = fopen(fullPath, 'r'); 
    for i = 1:startLine-1, fgetl(fid); end 
    raw = textscan(fid, '%f %f'); 
    fclose(fid); A = [raw{1}, raw{2}];
end